version: '2.2'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - MONGO_URI=mongodb+srv://jesserbk:STxq50ZR020XtaWT@cluster0.z6e0l6w.mongodb.net/globalup?retryWrites=true&w=majority&appName=Cluster0
    volumes:
      - ./uploads:/app/uploads
    restart: unless-stopped
